version: "3"
services:
 postgresql:
  image: postgres
  restart: always
  container_name: postgresql
  ports:
    - "5432:5432"
  volumes:
   - ./docker-pg-mult-db:/docker-entrypoint-initdb.d
  environment:
   - POSTGRES_MULTIPLE_DATABASES=axio
   - POSTGRES_USER=kong
   - POSTGRES_DB=kong
  healthcheck:
    test: ["CMD", "pg_isready", "-U", "kong"]
    interval: 10s
    timeout: 5s
    retries: 5
  logging:
    driver: "json-file"
    options:
      max-size: "200k"
      max-file: "10"
 kong-bootstrap:
  image: kong:1.3
  container_name: kong-bootstrap
  hostname: kongBootstrap
  depends_on:
   - postgresql
  restart: on-failure
  command: "kong migrations bootstrap"
  environment:
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_LOG_LEVEL=debug
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgresql
   - KONG_PG_USER=kong
 kong:
  image: kong:1.3
  container_name: kong
  hostname: kong
  depends_on:
   - postgresql
   - kong-bootstrap
  restart: always
  ports:
   - 8000:8000
   - 8001:8001
  environment:
   - KONG_ANONYMOUS_REPORTS=off
   - KONG_LOG_LEVEL=debug
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgresql
   - KONG_PG_USER=kong
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
 konga:
  image: pantsel/konga:latest
  container_name: konga
  ports:
   - "1337:1337"
  environment:
   - NODE_ENV=development
   - TOKEN_SECRET=MySecretPassPhrase
  depends_on:
   - kong
